### ISSUE TITLE
Incorrect page title

### ISSUE THREAD

**Issue by m-mujica** [bit-docs/bit-docs-docjs-theme#13]
<img width="451" alt="screen shot 2017-02-10 at 09 35 52" src="https://cloud.githubusercontent.com/assets/724877/22834993/626ce7d4-ef74-11e6-8498-a1bdcec5a8c6.png">

On the right is the current page title, note the missing "donejs" in the bit-docs version.

**Comment by chasenlehara** [comment]
I’m not seeing this issue on [this page](https://donejs.github.io/donejs-next/community.html) so I think this has been fixed.
